spring.application.name=EduMap
server.port=8080
spring.profiles.active=dev

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.ai.vectorstore.mariadb.initialize-schema=true
spring.jpa.hibernate.ddl-auto=update

