spring.application.name=EduMap
server.port=8080

# MySQL database username
spring.datasource.url=${MYSQL_URL}
# MySQL database username
spring.datasource.username=${MYSQL_USER}
# MySQL database password
spring.datasource.password=${MYSQL_PASS}

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key=${OPEN_ROUTER_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=arcee-ai/trinity-large-preview:free